# Generated by Django 4.0.4 on 2022-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=8)),
                ('price_on_sale', models.CharField(max_length=8)),
            ],
        ),
    ]
