# Generated by Django 4.0.4 on 2022-05-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='link',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
